insert into users(name, shortName, email, passwordHash, activationTimestamp) values("Sari van Veenendaal", "Sari", "sari@voetbal.nl", "fake", 1562771380672);
insert into users(name, shortName, email, passwordHash, activationTimestamp) values("Stefani van der Gragt", "Stefani", "stefani@voetbal.nl", "fake", 1562771380672);
insert into users(name, shortName, email, passwordHash, activationTimestamp) values("Dominique Bloodworth", "Dominique", "dominique@voetbal.nl", "fake", 1562771380672);
insert into users(name, shortName, email, passwordHash, activationTimestamp) values("Daniëlle van de Donk", "Daniëlle", "danielle@voetbal.nl", "fake", 1562771380672);
insert into users(name, shortName, email, passwordHash, activationTimestamp) values("Jill Roord", "Jill", "jill@voetbal.nl", "fake", 1562771380672);
insert into projects(name) values("WK 2019");
insert into projects(name) values("OS 2020");
insert into projects(name) values("WK 2021");
insert into members(userId, projectId) values((select id from users where shortName = "Sari"), (select id from projects where name = "WK 2019"));
insert into members(userId, projectId) values((select id from users where shortName = "Stefani"), (select id from projects where name = "WK 2019"));
insert into members(userId, projectId) values((select id from users where shortName = "Dominique"), (select id from projects where name = "WK 2019"));
insert into members(userId, projectId) values((select id from users where shortName = "Daniëlle"), (select id from projects where name = "WK 2019"));
insert into members(userId, projectId) values((select id from users where shortName = "Jill"), (select id from projects where name = "WK 2019"));
insert into members(userId, projectId) values((select id from users where shortName = "Sari"), (select id from projects where name = "OS 2020"));
insert into members(userId, projectId) values((select id from users where shortName = "Stefani"), (select id from projects where name = "OS 2020"));
insert into members(userId, projectId) values((select id from users where shortName = "Daniëlle"), (select id from projects where name = "OS 2020"));
insert into members(userId, projectId) values((select id from users where shortName = "Jill"), (select id from projects where name = "OS 2020"));
insert into members(userId, projectId) values((select id from users where shortName = "Sari"), (select id from projects where name = "WK 2021"));
insert into members(userId, projectId) values((select id from users where shortName = "Dominique"), (select id from projects where name = "WK 2021"));
insert into members(userId, projectId) values((select id from users where shortName = "Daniëlle"), (select id from projects where name = "WK 2021"));
